# Generated by Django 6.1 on 2026-09-16 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoBarras', models.CharField(max_length=100)),
                ('proteina', models.DecimalField(decimal_places=2, max_digits=6)),
                ('grasas', models.DecimalField(decimal_places=2, max_digits=6)),
                ('kCal', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(choices=[('0', 'Hombre'), ('1', 'Mujer'), ('2', 'Otro')], max_length=1)),
                ('porcentajegraso', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Ejercicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ejercicios', models.CharField(max_length=225)),
                ('musculo', models.CharField(max_length=225)),
                ('descripcion', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Entrenadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_clientes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fisioterapeutas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_clientes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Nutrisionistas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_clientes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('numero_identidad', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Dietas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='GMFitness.alimentos')),
            ],
        ),
        migrations.CreateModel(
            name='AsignarRutinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semanas', models.IntegerField()),
                ('dias', models.IntegerField()),
                ('series', models.IntegerField()),
                ('repeticiones', models.IntegerField()),
                ('intensidad', models.CharField(max_length=50)),
                ('estado_rutina', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='GMFitness.clientes')),
                ('entrenador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='GMFitness.entrenadores')),
            ],
        ),
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='GMFitness.clientes')),
                ('fisioterapeuta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='GMFitness.fisioterapeutas')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialEjercicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='GMFitness.asignarrutinas')),
            ],
        ),
        migrations.CreateModel(
            name='Membresias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateField()),
                ('tipos', models.CharField(choices=[('premium', 'PREMIUM'), ('gratuita', 'GRATUITA')], default='gratuita', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='GMFitness.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='AsignarDietas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carbosTotales', models.DecimalField(decimal_places=2, max_digits=6)),
                ('kCaloriasTotales', models.DecimalField(decimal_places=2, max_digits=6)),
                ('proteinasTotales', models.DecimalField(decimal_places=2, max_digits=6)),
                ('grasasTotales', models.DecimalField(decimal_places=2, max_digits=6)),
                ('estado_dieta', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='GMFitness.clientes')),
                ('dieta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='GMFitness.dietas')),
                ('nutrisionista', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='GMFitness.nutrisionistas')),
            ],
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField()),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'PENDIENTE'), ('rechazado', 'RECHAZADO'), ('confirmado', 'CONFIRMADO')], default='pendiente', max_length=20)),
                ('membresia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='GMFitness.membresias')),
            ],
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('numFactura', models.IntegerField(primary_key=True, serialize=False)),
                ('detalleFactura', models.CharField(max_length=300)),
                ('fechaFactura', models.DateField()),
                ('total', models.IntegerField()),
                ('pagos', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='GMFitness.pagos')),
            ],
        ),
        migrations.CreateModel(
            name='ProgresoClientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='GMFitness.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Rutinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='GMFitness.ejercicios')),
            ],
        ),
        migrations.AddField(
            model_name='asignarrutinas',
            name='rutina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='GMFitness.rutinas'),
        ),
        migrations.AddField(
            model_name='nutrisionistas',
            name='numero_identidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='GMFitness.usuarios'),
        ),
        migrations.AddField(
            model_name='fisioterapeutas',
            name='numero_identidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='GMFitness.usuarios'),
        ),
        migrations.AddField(
            model_name='entrenadores',
            name='numero_identidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='GMFitness.usuarios'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='numero_identidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='GMFitness.usuarios'),
        ),
    ]
